Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [19]:
import numpy as np
import pandas as pd
import seaborn as sns
df = sns.load_dataset("iris")
#df.head()
#df.describe()
df.iloc[0:1,0:3]

   sepal_length  sepal_width  petal_length
0           5.1          3.5           1.4

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [35]:
#df.iloc[0:100,-2:]
mask = df['petal_length'] > df['petal_length'].mean()
df[mask]
#df[mask].count()

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[93 rows x 5 columns]

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [45]:
df = sns.load_dataset("titanic")
#df.head()
#df.tail()
#df.info()
#df.describe()
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [63]:
femaleFirst = df[(df['sex'] == 'female') & (df['class'] == 'First')]
#femaleFirst
#femaleFirst['survived'].mean()
#df['survived'].mean()
if(df['survived'].mean() > femaleFirst['survived'].mean()):
    print("The survival rate of the filtered group is LESS than overall rate")
else:
    print("The survival rate of the filtered group is GREATER than overall rate")

The survival rate of the filtered group is GREATER than overall rate

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [89]:

#df['age'].fillna(df['age'].median(), inplace=True)
#df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
#df['embarked'].isna().sum()
#df.drop(columns=['deck'], inplace = True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [94]:
df['family_size'] = df['sibsp'] + df['parch'] + 1
df['is_alone'] = (df['family_size'] == 1).astype(int)
df.groupby('is_alone')['survived'].mean()
#df.head()

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [104]:
df = sns.load_dataset('tips')
#df.head()

avg_tip_day = df.groupby('day')['tip'].mean()
total_bill_gender = df.groupby('sex')['total_bill'].sum()
print(avg_tip_day)
print(total_bill_gender)

df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

best_day = df.groupby('day')['tip_percentage'].mean().idxmax()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64
sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

C:\Users\amank\AppData\Local\Temp\ipykernel_22588\2270952980.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_day = df.groupby('day')['tip'].mean()
C:\Users\amank\AppData\Local\Temp\ipykernel_22588\2270952980.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  total_bill_gender = df.groupby('sex')['total_bill'].sum()
C:\Users\amank\AppData\Local\Temp\ipykernel_22588\2270952980.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  best_day = df.groupby('day')['tip_percentage'].mean().idxmax()

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [107]:
df.head()
mask = (df['total_bill'] > 20) & (df['tip'] < 3)
df[mask]

filtered_data = df[mask][['total_bill', 'tip', 'sex', 'day', 'tip_percentage']]

filtered_data

     total_bill   tip     sex   day  tip_percentage
21        20.29  2.75  Female   Sat       13.553475
33        20.69  2.45  Female   Sat       11.841469
48        28.55  2.05    Male   Sun        7.180385
57        26.41  1.50  Female   Sat        5.679667
68        20.23  2.01    Male   Sat        9.935739
102       44.30  2.50  Female   Sat        5.643341
113       23.95  2.55    Male   Sun       10.647182
119       24.08  2.92  Female  Thur       12.126246
129       22.82  2.18    Male  Thur        9.553024
131       20.27  2.83  Female  Thur       13.961519
153       24.55  2.00    Male   Sun        8.146640
166       20.76  2.24    Male   Sun       10.789981
187       30.46  2.00    Male   Sun        6.565988
192       28.44  2.56    Male  Thur        9.001406
208       24.27  2.03    Male   Sat        8.364236
210       30.06  2.00    Male   Sat        6.653360
229       22.12  2.88  Female   Sat       13.019892
230       24.01  2.00    Male   Sat        8.329863
237       32.83  1.17    Male   Sat        3.563814
240       27.18  2.00  Female   Sat        7.358352
241       22.67  2.00    Male   Sat        8.822232

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [120]:
arr1 = np.array([[10,20], [30,40], [50,60]])
arr2 = np.array([[15,25], [35,45], [55,65]])
v = np.vstack([arr1, arr2])
h = np.hstack([arr1, arr2])
print(v)
print(h)
v_reshaped = v.reshape(2,6)
print(v_reshaped)
h_reshaped = h.reshape(2,6)
print(h_reshaped)

[[10 20]
 [30 40]
 [50 60]
 [15 25]
 [35 45]
 [55 65]]
[[10 20 15 25]
 [30 40 35 45]
 [50 60 55 65]]
[[10 20 30 40 50 60]
 [15 25 35 45 55 65]]
[[10 20 15 25 30 40]
 [35 45 50 60 55 65]]

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [135]:
df = sns.load_dataset('titanic')

def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    elif age > 60:
        return 'Senior'
    else:
        return 'Unknown' 

df['age_group'] = df['age'].apply(categorize_age)
df['age'].isna().sum()
#df.head()
survival_by_age = df.groupby('age_group')['survived'].mean()
print(survival_by_age)

age_group
Adult      0.386874
Child      0.539823
Senior     0.227273
Unknown    0.293785
Name: survived, dtype: float64

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [126]:
errors = np.random.randn(1000) 
#print(errors)
mean_error = np.mean(errors)
std_error = np.std(errors)
print(mean_error)
print(std_error)

0.07002515721124529
0.9676359579060826

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight